In [3]:
import pandas as pd
from sqlalchemy import create_engine
con = create_engine("mysql+pymysql://root:bhargav#7769@localhost:3306/INVENTORY_DB")

In [ ]:

pd.read_sql_query(" select * from purchase_prices  limit 5" , con)

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

In [ ]:
(pd.read_sql_query(" select count(*) as purchases from  purchases limit 5" , con),
pd.read_sql_query(" select count(*) as sales from  sales limit 5" , con),
pd.read_sql_query(" select count(*) as  purchase_prices from  purchase_prices limit 5" , con),
pd.read_sql_query(" select count(*) as  vendor_invoice  from  vendor_invoice limit 5" , con))

(   purchases
 0    2372474,
       sales
 0  12825363,
    purchase_prices
 0            12261,
    vendor_invoice
 0            5543)

In [ ]:
query = "SHOW TABLES"
tables = pd.read_sql(query, con)

# Show tables
print(tables)

  Tables_in_inventory_db
0        begin_inventory
1          end_inventory
2        purchase_prices
3              purchases
4                  sales
5         vendor_invoice

In [ ]:
tables.columns = ['name']  # Rename column

# Loop through tables and print record counts
for table in tables['name']:
    print('-'*50, f'{table}', '-'*50)
    count = pd.read_sql(f"SELECT COUNT(*) AS count FROM `{table}`", con)['count'].values[0]
    print('Count of records:', count)
    print()
    display(pd.read_sql_query(f"select * from {table} limit 5" , con))

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of records: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
Count of records: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of records: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- purchases --------------------------------------------------
Count of records: 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- sales --------------------------------------------------
Count of records: 12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

In [ ]:
purchaces = pd.read_sql_query(' select * from purchases  ',con)

In [ ]:
sales = pd.read_sql_query(' select * from sales where brand = 58 limit 3',con)

In [ ]:
purchaces.groupby(["Brand" , "PurchasePrice"])[['Quantity' , 'Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
58    9.28               3550  32944.00
60    7.40               1633  12084.20
61    10.60               312   3307.20
62    28.67              3200  91744.00
63    30.46              2855  86963.30
...                       ...       ...
90089 77.92                32   2493.44
90090 448.27                6   2689.62
90604 78.42               118   9253.56
90609 17.00               321   5457.00
90631 12.74              1938  24690.12

[10664 rows x 2 columns]

As the data that we need for analysis is distributed in different tables, we need to create a summary table containing:

purchase transactions made by vendors

sales transaction data

freight costs for each vendor

actual product prices from vendors

freight cost for each vendor

In [ ]:
pd.read_sql_query('select * from vendor_invoice limit 1',con)

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None

In [6]:
pd.read_sql_query(""" select 
                  VendorNumber ,
                  VendorName ,
                  sum(freight) as FrieghtCost 
                  from  
                  vendor_invoice 
                group by 
                  vendornumber , vendorname""" ,
                 con)

     VendorNumber                   VendorName  FrieghtCost
0             105  ALTAMAR BRANDS LLC                 62.39
1            4466  AMERICAN VINTAGE BEVERAGE         793.91
2             388  ATLANTIC IMPORTING COMPANY        211.74
3             480  BACARDI USA INC                 89286.27
4             516  BANFI PRODUCTS CORP              8510.41
..            ...                          ...          ...
124          4901  LAUREATE IMPORTS CO                 0.72
125         90059  BLACK COVE BEVERAGES               74.84
126          5083  LOYAL DOG WINERY                   10.68
127          1587  VINEYARD BRANDS LLC                54.23
128            54  AAPER ALCOHOL & CHEMICAL CO         0.48

[129 rows x 3 columns]

In [ ]:
(pd.read_sql_query( ' select * from purchases limit 0' , con),
pd.read_sql_query( ' select * from purchase_prices limit 0' , con))

(Empty DataFrame
 Columns: [InventoryId, Store, Brand, Description, Size, VendorNumber, VendorName, PONumber, PODate, ReceivingDate, InvoiceDate, PayDate, PurchasePrice, Quantity, Dollars, Classification]
 Index: [],
 Empty DataFrame
 Columns: [Brand, Description, Price, Size, Volume, Classification, PurchasePrice, VendorNumber, VendorName]
 Index: [])

In [4]:
pd.read_sql_query("""
            select 
                  p.VendorNumber,
                  p.VendorName,
                  p.Brand,
                  p.PurchasePrice,
                  pp.volume,
                  pp.price as ActualPrice,
                  sum(p.Quantity) As TotalPurchaseQuantity,
                  sum(p.dollars) As TotalPurchaseDollars
            from  purchases p 
            join
                  purchase_prices pp
                  on 
                  p.brand = pp.brand
            where p.purchasePrice > 0
            group by
                  p.VendorNumber,
                  p.VendorName ,
                  p.Brand , 
                  p.PurchasePrice,
                  pp.Volume,
                  pp.Price
                  order by TotalPurchaseDollars""" , con)

,VendorNumber,VendorName,Brand,PurchasePrice,volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,1.0,0.71
1,3960,DIAGEO NORTH AMERICA INC,6127,1.47,200,1.99,1.0,1.47
2,3924,HEAVEN HILL DISTILLERIES,9123,0.74,50,0.99,2.0,1.48
3,8004,SAZERAC CO INC,5683,0.39,50,0.49,6.0,2.34
4,9815,WINE GROUP INC,8527,1.32,750,4.99,2.0,2.64
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,138109.0,3023206.01
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,201682.0,3261197.94
10689,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,187407.0,3418303.68
10690,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,164038.0,3804041.22
10691,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,145080.0,3811251.60

In [ ]:
pd.read_sql_query(" select * from sales limit 0" ,con)

Empty DataFrame
Columns: [InventoryId, Store, Brand, Description, Size, SalesQuantity, SalesDollars, SalesPrice, SalesDate, Volume, Classification, ExciseTax, VendorNo, VendorName]
Index: []

In [3]:
pd.read_sql_query(""" 
              Select
                  VendorNo,
                  Brand,
                  sum(salesdollars) as TotalSalesDollars,
                  sum(salesprice) as TotalSalesPrice,
                  sum(salesQuantity) as TotalSalesQuantity
              from sales
              group by 
                  VendorNo,Brand
""", con)

       VendorNo  Brand  TotalSalesDollars  TotalSalesPrice  TotalSalesQuantity
0         12546   1004           15708.97         11365.46               703.0
1         12546   1005           32120.82         19349.47               918.0
2          2000  10058          293349.46        113447.03             21018.0
3         12546   1006            1308.72           323.19               328.0
4         10754  10062           18518.71         11417.50              2029.0
...         ...    ...                ...              ...                 ...
11267      4425  27700              88.99            88.99                 1.0
11268      4425  27851              37.98            37.98                 2.0
11269      2000  27969              36.99            36.99                 1.0
11270     12331    263              35.98            35.98                 2.0
11271      3924   9123               1.98             0.99                 2.0

[11272 rows x 5 columns]

creating final table

In [18]:
pd.read_sql_query(""" 
WITH FreightSummary AS (
    SELECT 
        VendorNumber,
        VendorName,
        SUM(freight) AS FreightCost
    FROM vendor_invoice 
    GROUP BY VendorNumber, VendorName
),
PurchaseSummary AS (
    SELECT 
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.PurchasePrice,
        pp.volume,
        pp.price AS ActualPrice,
        SUM(p.Quantity) AS TotalPurchaseQuantity,
        SUM(p.dollars) AS TotalPurchaseDollars
    FROM purchases p 
    JOIN purchase_prices pp
        ON p.brand = pp.brand
    WHERE p.PurchasePrice > 0
    GROUP BY
        p.VendorNumber,
        p.VendorName,
        p.Brand, 
        p.PurchasePrice,
        pp.Volume,
        pp.Price
),
SalesSummary AS (
    SELECT
        VendorNo,
        Brand,
        SUM(salesdollars) AS TotalSalesDollars,
        SUM(salesprice) AS TotalSalesPrice,
        SUM(salesQuantity) AS TotalSalesQuantity
    FROM sales
    GROUP BY VendorNo, Brand
)
SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,
    ss.TotalSalesQuantity,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    fs.FreightCost
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
    ON ps.Brand = ss.Brand AND ps.VendorNumber = ss.VendorNo
LEFT JOIN FreightSummary fs
    ON ps.VendorNumber = fs.VendorNumber                            
""", con)

,VendorNumber,VendorName,Brand,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,FreightCost
0,105,ALTAMAR BRANDS LLC,8412,35.71,49.99,750,320.0,11427.20,307.0,15346.93,12947.41,62.39
1,4466,AMERICAN VINTAGE BEVERAGE,5255,9.35,12.99,1750,6215.0,58110.25,6096.0,79187.04,51180.60,793.91
2,4466,AMERICAN VINTAGE BEVERAGE,5215,9.41,12.99,1750,4923.0,46325.43,4651.0,60416.49,41542.02,793.91
3,480,BACARDI USA INC,3348,22.38,29.99,1750,57349.0,1283470.62,56888.0,1766391.12,460087.95,89286.27
4,480,BACARDI USA INC,8358,14.49,19.99,750,7071.0,102458.79,8065.0,161219.35,87396.28,89286.27
...,...,...,...,...,...,...,...,...,...,...,...,...
12484,7153,PINE STATE TRADING CO,26508,6.81,10.49,750,1.0,6.81,1.0,10.49,10.49,15884.82
12485,8004,SAZERAC CO INC,2936,53.02,69.99,750,18.0,954.36,4.0,279.96,69.99,50293.62
12486,2000,SOUTHERN WINE & SPIRITS NE,26266,11.56,16.99,750,132.0,1525.92,2.0,33.98,16.99,18808.83
12487,2000,SOUTHERN WINE & SPIRITS NE,26266,11.56,16.99,750,132.0,1525.92,2.0,33.98,16.99,207.76
12488,9165,ULTRA BEVERAGE COMPANY LLP,1073,25.73,34.99,750,168.0,4322.64,NaN,NaN,NaN,68054.70

In [5]:
final_Table = pd.read_sql_query(""" 
WITH FreightSummary AS (
    SELECT 
        VendorNumber,
        VendorName,
        SUM(freight) AS FreightCost 
    FROM vendor_invoice 
    GROUP BY VendorNumber, VendorName
),
PurchaseSummary AS (
    SELECT 
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.PurchasePrice,
        pp.volume,
        pp.price AS ActualPrice,                       
        SUM(p.Quantity) AS TotalPurchaseQuantity,
        SUM(p.dollars) AS TotalPurchaseDollars
    FROM purchases p 
    JOIN purchase_prices pp ON p.brand = pp.brand
    WHERE p.PurchasePrice > 0
    GROUP BY
        p.VendorNumber,
        p.VendorName,
        p.Brand, 
        p.PurchasePrice,
        pp.Volume,
        pp.Price
),
SalesSummary AS (
    SELECT
        VendorNo,
        Brand,
        SUM(salesdollars) AS TotalSalesDollars,
        SUM(salesprice) AS TotalSalesPrice,
        SUM(salesQuantity) AS TotalSalesQuantity
    FROM sales 
    GROUP BY VendorNo, Brand
    HAVING SUM(salesdollars) > 0
)
SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,                            
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,                                                       
    ss.TotalSalesDollars,
    ss.TotalSalesQuantity,
    ss.TotalSalesPrice,
    fs.FreightCost
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
    ON ps.Brand = ss.Brand AND ps.VendorNumber = ss.VendorNo
LEFT JOIN FreightSummary fs
    ON ps.VendorNumber = fs.VendorNumber                            
""", con)

final_Table  # <- No print()

,VendorNumber,VendorName,Brand,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesDollars,TotalSalesQuantity,TotalSalesPrice,FreightCost
0,105,ALTAMAR BRANDS LLC,8412,35.71,49.99,750,320.0,11427.20,15346.93,307.0,12947.41,62.39
1,4466,AMERICAN VINTAGE BEVERAGE,5255,9.35,12.99,1750,6215.0,58110.25,79187.04,6096.0,51180.60,793.91
2,4466,AMERICAN VINTAGE BEVERAGE,5215,9.41,12.99,1750,4923.0,46325.43,60416.49,4651.0,41542.02,793.91
3,480,BACARDI USA INC,3348,22.38,29.99,1750,57349.0,1283470.62,1766391.12,56888.0,460087.95,89286.27
4,480,BACARDI USA INC,8358,14.49,19.99,750,7071.0,102458.79,161219.35,8065.0,87396.28,89286.27
...,...,...,...,...,...,...,...,...,...,...,...,...
12484,7153,PINE STATE TRADING CO,26508,6.81,10.49,750,1.0,6.81,10.49,1.0,10.49,15884.82
12485,8004,SAZERAC CO INC,2936,53.02,69.99,750,18.0,954.36,279.96,4.0,69.99,50293.62
12486,2000,SOUTHERN WINE & SPIRITS NE,26266,11.56,16.99,750,132.0,1525.92,33.98,2.0,16.99,18808.83
12487,2000,SOUTHERN WINE & SPIRITS NE,26266,11.56,16.99,750,132.0,1525.92,33.98,2.0,16.99,207.76
12488,9165,ULTRA BEVERAGE COMPANY LLP,1073,25.73,34.99,750,168.0,4322.64,NaN,NaN,NaN,68054.70

In [29]:
final_Table.describe()

,VendorNumber,Brand,PurchasePrice,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesDollars,TotalSalesQuantity,TotalSalesPrice,FreightCost
count,12489.000000,12489.000000,12489.000000,12489.000000,12489.000000,1.248900e+04,1.228000e+04,12280.000000,12280.000000,12489.000000
mean,9672.998799,18847.561134,24.892217,36.601191,2946.748178,2.840181e+04,4.073060e+04,2935.653827,17950.448936,52594.266657
std,17519.491679,12524.982470,103.582221,141.237886,10618.653774,1.203342e+05,1.648646e+05,10563.304099,43170.013577,60308.599732
min,2.000000,58.000000,0.360000,0.490000,1.000000,7.100000e-01,1.980000e+00,1.000000,0.990000,0.090000
25%,3960.000000,6919.000000,7.140000,10.990000,36.000000,4.728600e+02,8.707725e+02,36.000000,363.870000,6015.860000
50%,4425.000000,19693.000000,10.800000,16.990000,240.000000,3.545640e+03,5.469485e+03,260.000000,2933.865000,28720.520000
75%,9552.000000,25827.000000,20.430000,29.990000,1805.000000,1.922760e+04,2.727480e+04,1796.250000,15313.747500,68601.680000
max,201359.000000,90631.000000,5681.810000,7499.990000,337660.000000,3.811252e+06,5.101920e+06,334939.000000,672819.310000,257032.070000

In [37]:
final_Table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12489 entries, 0 to 12488
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorNumber           12489 non-null  int64
 1   VendorName             12489 non-null  object
 2   Brand                  12489 non-null  int64
 3   PurchasePrice          12489 non-null  float64
 4   ActualPrice            12489 non-null  float64
 5   Volume                 12489 non-null  float64
 6   TotalPurchaseQuantity  12489 non-null  float64
 7   TotalPurchaseDollars   12489 non-null  float64
 8   TotalSalesDollars      12489 non-null  float64
 9   TotalSalesQuantity     12489 non-null  float64
 10  TotalSalesPrice        12489 non-null  float64
 11  FreightCost            12489 non-null  float64
dtypes: float64(9), int64(2), object(1)
memory usage: 1.1+ MB

In [36]:
final_Table.isnull().sum()

VendorNumber             0
VendorName               0
Brand                    0
PurchasePrice            0
ActualPrice              0
Volume                   0
TotalPurchaseQuantity    0
TotalPurchaseDollars     0
TotalSalesDollars        0
TotalSalesQuantity       0
TotalSalesPrice          0
FreightCost              0
dtype: int64

In [33]:
final_Table['Volume'] = final_Table['Volume'].astype('float')

In [34]:
final_Table['VendorName'] = final_Table['VendorName'].astype('object')

In [35]:
final_Table.fillna(0 , inplace= True)

adding required columns

In [ ]:
#Adding Gross Profit
final_Table['GrossProfit'] = final_Table['TotalSalesDollars'] - final_Table['TotalPurchaseDollars']

In [39]:
final_Table

,VendorNumber,VendorName,Brand,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesDollars,TotalSalesQuantity,TotalSalesPrice,FreightCost,GrossProfit
0,105,ALTAMAR BRANDS LLC,8412,35.71,49.99,750.0,320.0,11427.20,15346.93,307.0,12947.41,62.39,3919.73
1,4466,AMERICAN VINTAGE BEVERAGE,5255,9.35,12.99,1750.0,6215.0,58110.25,79187.04,6096.0,51180.60,793.91,21076.79
2,4466,AMERICAN VINTAGE BEVERAGE,5215,9.41,12.99,1750.0,4923.0,46325.43,60416.49,4651.0,41542.02,793.91,14091.06
3,480,BACARDI USA INC,3348,22.38,29.99,1750.0,57349.0,1283470.62,1766391.12,56888.0,460087.95,89286.27,482920.50
4,480,BACARDI USA INC,8358,14.49,19.99,750.0,7071.0,102458.79,161219.35,8065.0,87396.28,89286.27,58760.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12484,7153,PINE STATE TRADING CO,26508,6.81,10.49,750.0,1.0,6.81,10.49,1.0,10.49,15884.82,3.68
12485,8004,SAZERAC CO INC,2936,53.02,69.99,750.0,18.0,954.36,279.96,4.0,69.99,50293.62,-674.40
12486,2000,SOUTHERN WINE & SPIRITS NE,26266,11.56,16.99,750.0,132.0,1525.92,33.98,2.0,16.99,18808.83,-1491.94
12487,2000,SOUTHERN WINE & SPIRITS NE,26266,11.56,16.99,750.0,132.0,1525.92,33.98,2.0,16.99,207.76,-1491.94
12488,9165,ULTRA BEVERAGE COMPANY LLP,1073,25.73,34.99,750.0,168.0,4322.64,0.00,0.0,0.00,68054.70,-4322.64

In [42]:
#Adding Profit Margin

final_Table['ProfitMargin'] = (final_Table['GrossProfit'] / final_Table['TotalSalesDollars']) * 100

final_Table

,VendorNumber,VendorName,Brand,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesDollars,TotalSalesQuantity,TotalSalesPrice,FreightCost,GrossProfit,ProfitMargin
0,105,ALTAMAR BRANDS LLC,8412,35.71,49.99,750.0,320.0,11427.20,15346.93,307.0,12947.41,62.39,3919.73,25.540808
1,4466,AMERICAN VINTAGE BEVERAGE,5255,9.35,12.99,1750.0,6215.0,58110.25,79187.04,6096.0,51180.60,793.91,21076.79,26.616464
2,4466,AMERICAN VINTAGE BEVERAGE,5215,9.41,12.99,1750.0,4923.0,46325.43,60416.49,4651.0,41542.02,793.91,14091.06,23.323202
3,480,BACARDI USA INC,3348,22.38,29.99,1750.0,57349.0,1283470.62,1766391.12,56888.0,460087.95,89286.27,482920.50,27.339387
4,480,BACARDI USA INC,8358,14.49,19.99,750.0,7071.0,102458.79,161219.35,8065.0,87396.28,89286.27,58760.56,36.447585
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12484,7153,PINE STATE TRADING CO,26508,6.81,10.49,750.0,1.0,6.81,10.49,1.0,10.49,15884.82,3.68,35.081030
12485,8004,SAZERAC CO INC,2936,53.02,69.99,750.0,18.0,954.36,279.96,4.0,69.99,50293.62,-674.40,-240.891556
12486,2000,SOUTHERN WINE & SPIRITS NE,26266,11.56,16.99,750.0,132.0,1525.92,33.98,2.0,16.99,18808.83,-1491.94,-4390.641554
12487,2000,SOUTHERN WINE & SPIRITS NE,26266,11.56,16.99,750.0,132.0,1525.92,33.98,2.0,16.99,207.76,-1491.94,-4390.641554
12488,9165,ULTRA BEVERAGE COMPANY LLP,1073,25.73,34.99,750.0,168.0,4322.64,0.00,0.0,0.00,68054.70,-4322.64,-inf

In [43]:
#Adding Stock turnover

final_Table['StockTurnover'] = final_Table['TotalSalesQuantity'] / final_Table['TotalPurchaseQuantity']

final_Table

,VendorNumber,VendorName,Brand,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesDollars,TotalSalesQuantity,TotalSalesPrice,FreightCost,GrossProfit,ProfitMargin,StockTurnover
0,105,ALTAMAR BRANDS LLC,8412,35.71,49.99,750.0,320.0,11427.20,15346.93,307.0,12947.41,62.39,3919.73,25.540808,0.959375
1,4466,AMERICAN VINTAGE BEVERAGE,5255,9.35,12.99,1750.0,6215.0,58110.25,79187.04,6096.0,51180.60,793.91,21076.79,26.616464,0.980853
2,4466,AMERICAN VINTAGE BEVERAGE,5215,9.41,12.99,1750.0,4923.0,46325.43,60416.49,4651.0,41542.02,793.91,14091.06,23.323202,0.944749
3,480,BACARDI USA INC,3348,22.38,29.99,1750.0,57349.0,1283470.62,1766391.12,56888.0,460087.95,89286.27,482920.50,27.339387,0.991961
4,480,BACARDI USA INC,8358,14.49,19.99,750.0,7071.0,102458.79,161219.35,8065.0,87396.28,89286.27,58760.56,36.447585,1.140574
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12484,7153,PINE STATE TRADING CO,26508,6.81,10.49,750.0,1.0,6.81,10.49,1.0,10.49,15884.82,3.68,35.081030,1.000000
12485,8004,SAZERAC CO INC,2936,53.02,69.99,750.0,18.0,954.36,279.96,4.0,69.99,50293.62,-674.40,-240.891556,0.222222
12486,2000,SOUTHERN WINE & SPIRITS NE,26266,11.56,16.99,750.0,132.0,1525.92,33.98,2.0,16.99,18808.83,-1491.94,-4390.641554,0.015152
12487,2000,SOUTHERN WINE & SPIRITS NE,26266,11.56,16.99,750.0,132.0,1525.92,33.98,2.0,16.99,207.76,-1491.94,-4390.641554,0.015152
12488,9165,ULTRA BEVERAGE COMPANY LLP,1073,25.73,34.99,750.0,168.0,4322.64,0.00,0.0,0.00,68054.70,-4322.64,-inf,0.000000

In [44]:
#Adding SalesToPurchaseRatio

final_Table['SalesToPurchaseRatio'] = final_Table['TotalSalesDollars'] / final_Table['TotalPurchaseDollars']

final_Table

,VendorNumber,VendorName,Brand,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesDollars,TotalSalesQuantity,TotalSalesPrice,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesToPurchaseRatio
0,105,ALTAMAR BRANDS LLC,8412,35.71,49.99,750.0,320.0,11427.20,15346.93,307.0,12947.41,62.39,3919.73,25.540808,0.959375,1.343018
1,4466,AMERICAN VINTAGE BEVERAGE,5255,9.35,12.99,1750.0,6215.0,58110.25,79187.04,6096.0,51180.60,793.91,21076.79,26.616464,0.980853,1.362703
2,4466,AMERICAN VINTAGE BEVERAGE,5215,9.41,12.99,1750.0,4923.0,46325.43,60416.49,4651.0,41542.02,793.91,14091.06,23.323202,0.944749,1.304175
3,480,BACARDI USA INC,3348,22.38,29.99,1750.0,57349.0,1283470.62,1766391.12,56888.0,460087.95,89286.27,482920.50,27.339387,0.991961,1.376261
4,480,BACARDI USA INC,8358,14.49,19.99,750.0,7071.0,102458.79,161219.35,8065.0,87396.28,89286.27,58760.56,36.447585,1.140574,1.573504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12484,7153,PINE STATE TRADING CO,26508,6.81,10.49,750.0,1.0,6.81,10.49,1.0,10.49,15884.82,3.68,35.081030,1.000000,1.540382
12485,8004,SAZERAC CO INC,2936,53.02,69.99,750.0,18.0,954.36,279.96,4.0,69.99,50293.62,-674.40,-240.891556,0.222222,0.293348
12486,2000,SOUTHERN WINE & SPIRITS NE,26266,11.56,16.99,750.0,132.0,1525.92,33.98,2.0,16.99,18808.83,-1491.94,-4390.641554,0.015152,0.022269
12487,2000,SOUTHERN WINE & SPIRITS NE,26266,11.56,16.99,750.0,132.0,1525.92,33.98,2.0,16.99,207.76,-1491.94,-4390.641554,0.015152,0.022269
12488,9165,ULTRA BEVERAGE COMPANY LLP,1073,25.73,34.99,750.0,168.0,4322.64,0.00,0.0,0.00,68054.70,-4322.64,-inf,0.000000,0.000000

In [48]:
import numpy as np
final_Table.replace([np.inf, -np.inf], np.nan, inplace=True)
final_Table.dropna(inplace=True)
final_Table

,VendorNumber,VendorName,Brand,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesDollars,TotalSalesQuantity,TotalSalesPrice,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesToPurchaseRatio
0,105,ALTAMAR BRANDS LLC,8412,35.71,49.99,750.0,320.0,11427.20,15346.93,307.0,12947.41,62.39,3919.73,25.540808,0.959375,1.343018
1,4466,AMERICAN VINTAGE BEVERAGE,5255,9.35,12.99,1750.0,6215.0,58110.25,79187.04,6096.0,51180.60,793.91,21076.79,26.616464,0.980853,1.362703
2,4466,AMERICAN VINTAGE BEVERAGE,5215,9.41,12.99,1750.0,4923.0,46325.43,60416.49,4651.0,41542.02,793.91,14091.06,23.323202,0.944749,1.304175
3,480,BACARDI USA INC,3348,22.38,29.99,1750.0,57349.0,1283470.62,1766391.12,56888.0,460087.95,89286.27,482920.50,27.339387,0.991961,1.376261
4,480,BACARDI USA INC,8358,14.49,19.99,750.0,7071.0,102458.79,161219.35,8065.0,87396.28,89286.27,58760.56,36.447585,1.140574,1.573504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12479,4425,MARTIGNETTI COMPANIES,27886,10.06,14.99,750.0,1416.0,14244.96,1154.23,77.0,374.75,144719.92,-13090.73,-1134.152639,0.054379,0.081027
12484,7153,PINE STATE TRADING CO,26508,6.81,10.49,750.0,1.0,6.81,10.49,1.0,10.49,15884.82,3.68,35.081030,1.000000,1.540382
12485,8004,SAZERAC CO INC,2936,53.02,69.99,750.0,18.0,954.36,279.96,4.0,69.99,50293.62,-674.40,-240.891556,0.222222,0.293348
12486,2000,SOUTHERN WINE & SPIRITS NE,26266,11.56,16.99,750.0,132.0,1525.92,33.98,2.0,16.99,18808.83,-1491.94,-4390.641554,0.015152,0.022269
12487,2000,SOUTHERN WINE & SPIRITS NE,26266,11.56,16.99,750.0,132.0,1525.92,33.98,2.0,16.99,207.76,-1491.94,-4390.641554,0.015152,0.022269

In [55]:
final_Table.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12280 entries, 0 to 12487
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorNumber           12280 non-null  int64
 1   VendorName             12280 non-null  object
 2   Brand                  12280 non-null  int64
 3   PurchasePrice          12280 non-null  float64
 4   ActualPrice            12280 non-null  float64
 5   Volume                 12280 non-null  float64
 6   TotalPurchaseQuantity  12280 non-null  float64
 7   TotalPurchaseDollars   12280 non-null  float64
 8   TotalSalesDollars      12280 non-null  float64
 9   TotalSalesQuantity     12280 non-null  float64
 10  TotalSalesPrice        12280 non-null  float64
 11  FreightCost            12280 non-null  float64
 12  GrossProfit            12280 non-null  float64
 13  ProfitMargin           12280 non-null  float64
 14  StockTurnover          12280 non-null  float64
 15  SalesToPurchaseRatio   12280 non-null  float64
dtypes: float64(13), int64(2), object(1)
memory usage: 1.6+ MB

In [57]:
engine = create_engine("mysql+pymysql://root:bhargav#7769@localhost:3306/inventory_db")
final_Table.to_sql(name='sales_summary', con=engine, index=False, if_exists='replace')

12280

In [62]:
pd.read_sql_query(' select * from sales_summary limit 0' ,engine)

Empty DataFrame
Columns: [VendorNumber, VendorName, Brand, PurchasePrice, ActualPrice, Volume, TotalPurchaseQuantity, TotalPurchaseDollars, TotalSalesDollars, TotalSalesQuantity, TotalSalesPrice, FreightCost, GrossProfit, ProfitMargin, StockTurnover, SalesToPurchaseRatio]
Index: []